#ifndef CURL_CONFIG_H
#define CURL_CONFIG_H

#define CURL_OS "Android"

#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDBOOL_H 1

#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1

#define HAVE_NETINET_IN_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_NETDB_H 1

#define HAVE_SOCKET 1
#define HAVE_RECV 1
#define HAVE_SEND 1
#define HAVE_SELECT 1
#define HAVE_POLL_H 1

#define HAVE_GETADDRINFO 1
#define HAVE_FREEADDRINFO 1
#define HAVE_GAI_STRERROR 1

#define HAVE_INET_PTON 1
#define HAVE_INET_NTOP 1
#define HAVE_FCNTL 1
#define HAVE_GETTIMEOFDAY 1

#define HAVE_STRUCT_TIMEVAL 1

#define SIZEOF_INT 4
#define SIZEOF_LONG 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_SIZE_T 4
#define SIZEOF_OFF_T 4
#define SIZEOF_CURL_OFF_T 8

#define CURL_DISABLE_LDAP 1
#define CURL_DISABLE_LDAPS 1
#define CURL_DISABLE_FTP 1
#define CURL_DISABLE_TFTP 1
#define CURL_DISABLE_TELNET 1
#define CURL_DISABLE_DICT 1
#define CURL_DISABLE_FILE 1
#define CURL_DISABLE_RTSP 1
#define CURL_DISABLE_SMB 1
#define CURL_DISABLE_SMTP 1
#define CURL_DISABLE_IMAP 1
#define CURL_DISABLE_POP3 1
#define CURL_DISABLE_MQTT 1
#define CURL_DISABLE_GOPHER 1
#define CURL_DISABLE_SOCKS 1
#define CURL_DISABLE_KERBEROS 1
#define CURL_DISABLE_PROXY 1
#define CURL_DISABLE_UNIX_SOCKETS 1

#define CURL_DISABLE_COOKIES 0
#define CURL_DISABLE_HTTP_AUTH 0

#endif